# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Atmosphere
      - name: Get latest release of Atmosphere
        uses: rez0n/actions-github-release@v1.8
        id: atmosphere_release
        env:
          repository: "ELY3M/Atmosphere"
          type: "stable"
      
      - name: Download and unzip Atmosphere
        uses: schmiddim/action-wget-unzip@v2
        id: unzip_atmosphere
        with:
          url: ${{ steps.atmosphere_release.outputs.browser_download_url }}
          destination: ns-release
          
      # Hekate
      - name: Get latest release of Hekate
        uses: rez0n/actions-github-release@v1.8
        id: hekate_release
        env:
          repository: "CTCaer/hekate"
          type: "stable"
      
      - name: Download and unzip Hekate
        uses: schmiddim/action-wget-unzip@v2
        id: unzip_hekate
        with:
          url: ${{ steps.hekate_release.outputs.browser_download_url }}
          destination: ns-release
          
      # Patches
      - name: Get latest release of patches
        uses: rez0n/actions-github-release@v1.8
        id: patches_release
        env:
          repository: "ITotalJustice/patches"
          type: "stable"
      
      - name: Download and unzip patches
        uses: schmiddim/action-wget-unzip@v2
        id: unzip_patches
        with:
          url: ${{ steps.patches_release.outputs.browser_download_url }}
          destination: ns-release
          
      - name: Zip all files
        run: | 
          echo ${{ steps.atmosphere_release.outputs.browser_download_url }}
          echo ${{ steps.hekate_release.outputs.browser_download_url }}
          echo ${{ steps.patches_release.outputs.browser_download_url }}
          zip -qr ns-release.zip ns-release
          touch CHANGELOG.log
          echo "Atmosphere - ${{ steps.atmosphere_release.outputs.release }}">>CHANGELOG.log
          echo "Hekate - ${{ steps.hekate_release.outputs.release }}">>CHANGELOG.log
          echo "Patches - ${{ steps.patches_release.outputs.release }}">>CHANGELOG.log
          ls
          
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.NS_ACTION }}
          tag_name: latest
          name: Development Build
          body_path: CHANGELOG.log
          files: |
            ns-release.zip
