# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Preparing
      - name: Preparing
        run: |
          mkdir ns-release
          mkdir overlays
          mkdir contents
          mkdir switch/EdiZon -p
          touch CHANGELOG.md

      # Atmosphere
      - name: Get latest release of Atmosphere
        uses: rez0n/actions-github-release@v1.8
        id: atmosphere_release
        env:
          repository: ELY3M/Atmosphere
          type: latest

      # Hekate
      - name: Get latest release of Hekate
        uses: rez0n/actions-github-release@v1.8
        id: hekate_release
        env:
          repository: CTCaer/hekate
          type: latest

      # Patches
      - name: Get latest release of patches
        uses: rez0n/actions-github-release@v1.8
        id: patches_release
        env:
          repository: ITotalJustice/patches
          type: latest

      # Tesla-Menu
      - name: Get latest release of Tesla-Menu
        uses: rez0n/actions-github-release@v1.8
        id: teslaMenu_release
        env:
          repository: WerWolv/Tesla-Menu
          type: latest

      # Emuiibo
      - name: Get latest release of emuiibo
        uses: rez0n/actions-github-release@v1.8
        id: emuiibo_release
        env:
          repository: XorTroll/emuiibo
          type: latest

      # EdiZon
      - name: Get latest release of EdiZon
        uses: andy-v-h/get-release-asset-action@v1.1.0
        id: EdiZon_release
        with:
          repo: WerWolv/EdiZon
          match: EdiZon.nro
          rename: switch/EdiZon/EdiZon.nro

      # ovlEdiZon
      - name: Get latest release of ovlEdiZon
        uses: andy-v-h/get-release-asset-action@v1.1.0
        id: ovlEdiZon_release
        with:
          repo: WerWolv/EdiZon
          match: ovlEdiZon.ovl
          rename: overlays/ovlEdiZon.ovl

      # ovlSysmodules
      - name: Get latest release of ovlSysmodules
        uses: andy-v-h/get-release-asset-action@v1.1.0
        id: ovlSysmodules_release
        with:
          repo: WerWolv/ovl-sysmodules
          match: ovlSysmodules.ovl
          rename: overlays/ovlSysmodules.ovl

      # Get release and unzip archives
      - name: Wget and unzip archives
        run: |
          wget -O atmosphere.zip ${{ steps.atmosphere_release.outputs.browser_download_url }}
          wget -O hekate.zip ${{ steps.hekate_release.outputs.browser_download_url }}
          wget -O patches.zip ${{ steps.patches_release.outputs.browser_download_url }}
          unzip atmosphere.zip -d ns-release
          unzip -n hekate.zip -d ns-release
          unzip -o patches.zip -d ns-release
          rm atmosphere.zip hekate.zip patches.zip

      # Get release and unzip overlays
      - name: Wget and unzip overlays
        run: |
          wget -O tesla-menu.zip ${{ steps.teslaMenu_release.outputs.browser_download_url }}
          unzip tesla-menu.zip switch/.overlays/ovlmenu.ovl -d overlays -j
          rm tesla-menu.zip
          wget -O emuiibo.zip ${{ steps.emuiibo_release.outputs.browser_download_url }}
          unzip emuiibo.zip SdOut/switch/.overlays/emuiibo.ovl -d overlays -j
          unzip emuiibo.zip SdOut/atmosphere/contents/ -d contents -j
          rm emuiibo.zip

      # Checkout custom files
      - name: Checkout custom files
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.NS_ACTION }}
          path: git

      # Merge files
      - name: Merge files
        run: |
          cp -rf git/[!.]* ns-release
          mv ns-release/hekate_ctcaer*.bin ns-release/payload.bin
          mv overlays ns-release/switch/.overlays
          mv contents/* ns-release/atmosphere/contents
          mv switch/* ns-release/switch

      # Zip all files
      - name: Zip all files
        run: |
          cd ns-release
          zip -qr ../ns-release.zip *
          cd ..
          echo "Atmosphere - ${{ steps.atmosphere_release.outputs.release }}">>CHANGELOG.md
          echo "Hekate - ${{ steps.hekate_release.outputs.release }}">>CHANGELOG.md
          echo "Patches - ${{ steps.patches_release.outputs.release }}">>CHANGELOG.md
          ls

      # Build and upload
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.NS_ACTION }}
          tag_name: latest
          name: Development Build
          body_path: CHANGELOG.md
          files: |
            ns-release.zip
